[tool.poetry]
name = "Odoo Server 16.0"
version = "16.0.20240214"
description = "Odoo Server repackaged with Poetry"
authors = ["Martel IT"]
license = "LGPL-3.0-only"
readme = "README.md"

packages = [{include = "odoo"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"  # Support both Python 3.11 and 3.12

# Core Dependencies
Babel = "2.9.1"
chardet = "4.0.0"
cryptography = "3.4.8"
decorator = "4.4.2"
docutils = "0.16"
ebaysdk = "2.1.5"
freezegun = "0.3.15"
gevent = "21.8.0"
greenlet = "1.1.2"
idna = "2.10"
Jinja2 = "3.1.2"  # Corretta la versione per Python >3.10
libsass = "0.20.1"
lxml = "4.9.3"
MarkupSafe = "2.1.2"
num2words = "0.5.9"
ofxparse = "0.21"
passlib = "1.7.4"
Pillow = "9.4.0"
polib = "1.1.0"
psutil = "5.9.4"
psycopg2 = "2.9.5"
pydot = "1.4.2"
pyopenssl = "20.0.1"
PyPDF2 = "2.12.1"
pyserial = "3.5"
python-dateutil = "2.8.1"
python-ldap = "3.4.0"
python-stdnum = "1.16"
pytz = "*"
pyusb = "1.2.1"
qrcode = "6.1"
reportlab = "3.6.12"
requests = "2.25.1"
urllib3 = "1.26.5"
vobject = "0.9.6.1"
Werkzeug = "2.0.2"
xlrd = "1.2.0"
XlsxWriter = "1.1.2"
xlwt = "1.3.0"
zeep = "4.0.0"
attrs = "22.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
